### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by purrgrammer** [PIWEEK/coco-material-front#2]
Is this the right place to make requests about illustrations that could be added to Coco Material? Do you intend to keep adding more? Thanks for the cool project 🎉

**Comment by EstherMoreno** [comment]
Yes! We are adding more illustrations so you can make requests here : )

**Comment by purrgrammer** [comment]
If you could add illustration for the major browsers (Firefox, Internet Explorer, Chrome, Edge) it'd be awesome! 

Muy chulas las ilustraciones Esther, estoy usando algunas en un proyectillo personal 😊

**Comment by EstherMoreno** [comment]
Qué guay que las estés usando :D y muy buena sugerencia, tomo nota! ;)

**Comment by EstherMoreno** [comment]
Pues ya los tienes en cocomaterial! por browser y logo :)

**Comment by purrgrammer** [comment]
Muchísimas gracias 🎉

**Comment by EstherMoreno** [comment]
Pensé que Edge había sustituído totalmente a Explorer pero veo que no :-S. Lo haré hoy y lo subo luego ;)
